-- MySQL Script generated by MySQL Workbench
-- 05/20/15 12:56:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema transmilenio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `transmilenio` ;

-- -----------------------------------------------------
-- Schema transmilenio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `transmilenio` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `transmilenio` ;

-- -----------------------------------------------------
-- Table `transmilenio`.`troncal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `transmilenio`.`troncal` ;

CREATE TABLE IF NOT EXISTS `transmilenio`.`troncal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transmilenio`.`estacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `transmilenio`.`estacion` ;

CREATE TABLE IF NOT EXISTS `transmilenio`.`estacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `troncal_id` INT NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `direccion` VARCHAR(200) NOT NULL,
  `plano` VARCHAR(2083) NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estacion_troncal_idx` (`troncal_id` ASC),
  CONSTRAINT `fk_estacion_troncal`
    FOREIGN KEY (`troncal_id`)
    REFERENCES `transmilenio`.`troncal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transmilenio`.`ruta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `transmilenio`.`ruta` ;

CREATE TABLE IF NOT EXISTS `transmilenio`.`ruta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(200) NOT NULL,
  `horario_lun_vie` VARCHAR(200) NULL,
  `horario_sab` VARCHAR(200) NULL,
  `horario_dom_fes` VARCHAR(200) NULL,
  `imagen` VARCHAR(2083) NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transmilenio`.`estacion_has_ruta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `transmilenio`.`estacion_has_ruta` ;

CREATE TABLE IF NOT EXISTS `transmilenio`.`estacion_has_ruta` (
  `estacion_id` INT NOT NULL,
  `ruta_id` INT NOT NULL,
  PRIMARY KEY (`estacion_id`, `ruta_id`),
  INDEX `fk_estacion_has_ruta_ruta1_idx` (`ruta_id` ASC),
  INDEX `fk_estacion_has_ruta_estacion1_idx` (`estacion_id` ASC),
  CONSTRAINT `fk_estacion_has_ruta_estacion1`
    FOREIGN KEY (`estacion_id`)
    REFERENCES `transmilenio`.`estacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estacion_has_ruta_ruta1`
    FOREIGN KEY (`ruta_id`)
    REFERENCES `transmilenio`.`ruta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transmilenio`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `transmilenio`.`usuario` ;

CREATE TABLE IF NOT EXISTS `transmilenio`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(200) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `transmilenio`.`troncal`
-- -----------------------------------------------------
START TRANSACTION;
USE `transmilenio`;
INSERT INTO `transmilenio`.`troncal` (`id`, `nombre`, `estado`) VALUES (1, 'Americas', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `transmilenio`.`estacion`
-- -----------------------------------------------------
START TRANSACTION;
USE `transmilenio`;
INSERT INTO `transmilenio`.`estacion` (`id`, `troncal_id`, `nombre`, `direccion`, `plano`, `estado`) VALUES (1, 1, 'Portal de las Americas', 'Ave. Cali - Calle 43 Sur', NULL, 1);
INSERT INTO `transmilenio`.`estacion` (`id`, `troncal_id`, `nombre`, `direccion`, `plano`, `estado`) VALUES (2, 1, 'Patio Bonito', 'Ave. Cali - Calle 40 Sur', NULL, 1);
INSERT INTO `transmilenio`.`estacion` (`id`, `troncal_id`, `nombre`, `direccion`, `plano`, `estado`) VALUES (3, 1, 'Biblioteca Tintal', 'Ave. Cali - Calle 33 Sur', NULL, 1);
INSERT INTO `transmilenio`.`estacion` (`id`, `troncal_id`, `nombre`, `direccion`, `plano`, `estado`) VALUES (4, 1, 'Tv 86', 'Ave. Americas - Carrera 79D', NULL, 1);
INSERT INTO `transmilenio`.`estacion` (`id`, `troncal_id`, `nombre`, `direccion`, `plano`, `estado`) VALUES (5, 1, 'Banderas', 'Ave. Americas - Carrera 78A', NULL, 1);
INSERT INTO `transmilenio`.`estacion` (`id`, `troncal_id`, `nombre`, `direccion`, `plano`, `estado`) VALUES (6, 1, 'Mandalay', 'Ave. Americas - Carrera 73Bis', NULL, 1);
INSERT INTO `transmilenio`.`estacion` (`id`, `troncal_id`, `nombre`, `direccion`, `plano`, `estado`) VALUES (7, 1, 'Mundo Aventura', 'Ave. Americas - Carrera 71B', NULL, 1);
INSERT INTO `transmilenio`.`estacion` (`id`, `troncal_id`, `nombre`, `direccion`, `plano`, `estado`) VALUES (8, 1, 'Marsella', 'Ave. Americas - Carrera 69C', NULL, 1);
INSERT INTO `transmilenio`.`estacion` (`id`, `troncal_id`, `nombre`, `direccion`, `plano`, `estado`) VALUES (9, 1, 'Pradera', 'Ave. Americas - Carrera 65', NULL, 1);
INSERT INTO `transmilenio`.`estacion` (`id`, `troncal_id`, `nombre`, `direccion`, `plano`, `estado`) VALUES (10, 1, 'Americas Cr 53A', 'Ave. Americas - Cra 53A', NULL, 1);
INSERT INTO `transmilenio`.`estacion` (`id`, `troncal_id`, `nombre`, `direccion`, `plano`, `estado`) VALUES (11, 1, 'Puente Aranda', 'Calle 13 - Carrera 48', NULL, 1);
INSERT INTO `transmilenio`.`estacion` (`id`, `troncal_id`, `nombre`, `direccion`, `plano`, `estado`) VALUES (12, 1, 'Carrera 43', 'Calle 13 - Carrera 42B', NULL, 1);
INSERT INTO `transmilenio`.`estacion` (`id`, `troncal_id`, `nombre`, `direccion`, `plano`, `estado`) VALUES (13, 1, 'Zona Industrial', 'Calle 13 - Carrera 38', NULL, 1);
INSERT INTO `transmilenio`.`estacion` (`id`, `troncal_id`, `nombre`, `direccion`, `plano`, `estado`) VALUES (14, 1, 'CDS Carrera 32', 'Calle 13 - Carrera 32', NULL, 1);
INSERT INTO `transmilenio`.`estacion` (`id`, `troncal_id`, `nombre`, `direccion`, `plano`, `estado`) VALUES (15, 1, 'Ricaurte', 'Calle 13 - Carrera 28', NULL, 1);
INSERT INTO `transmilenio`.`estacion` (`id`, `troncal_id`, `nombre`, `direccion`, `plano`, `estado`) VALUES (16, 1, 'San Façon - Cra.22', 'Calle 13 - Carrera 22', NULL, 1);
INSERT INTO `transmilenio`.`estacion` (`id`, `troncal_id`, `nombre`, `direccion`, `plano`, `estado`) VALUES (17, 1, 'De la Sabana', 'Calle 13 - Carrera 16Bis', NULL, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `transmilenio`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `transmilenio`;
INSERT INTO `transmilenio`.`usuario` (`id`, `username`, `password`, `estado`) VALUES (DEFAULT, 'admin', 'admin', 1);

COMMIT;

